#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="$REPO_ROOT/.clangd"
MODE="${1:-}"

if [ -z "$MODE" ]; then
  if [ ! -f "$TARGET" ]; then
    echo "none"
  elif grep -q "XPU_CUDA" "$TARGET"; then
    echo "cuda"
  else
    echo "cpu"
  fi
  exit 0
fi

if [ "$MODE" != "cpu" ] && [ "$MODE" != "cuda" ]; then
  echo "usage: scripts/clangd-mode.sh [cpu|cuda]" >&2
  exit 1
fi

TEMPLATE="$REPO_ROOT/.clangd-$MODE"

if [ ! -f "$TEMPLATE" ]; then
  echo "missing $TEMPLATE" >&2
  exit 1
fi

find_compile_db() {
  if [ -n "${VMC_CLANGD_DB:-}" ]; then
    echo "$VMC_CLANGD_DB"
    return
  fi

  find "$REPO_ROOT" -mindepth 2 -maxdepth 2 -name compile_commands.json -printf '%T@ %h\n' \
    | sort -rn \
    | head -n 1 \
    | cut -d' ' -f2-
}

find_cuda_path() {
  if [ -n "${CUDA_HOME:-}" ]; then
    echo "$CUDA_HOME"
  elif [ -n "${CUDA_PATH:-}" ]; then
    echo "$CUDA_PATH"
  elif nvcc_bin="$(command -v nvcc)"; then
    dirname "$(dirname "$(readlink -f "$nvcc_bin")")"
  elif [ -d /usr/local/cuda ]; then
    echo "/usr/local/cuda"
  fi
}

find_cccl_include() {
  local cuda_path="$1"

  if [ -z "$cuda_path" ]; then
    return
  fi

  find "$cuda_path" -maxdepth 4 -type d -name cccl 2>/dev/null | head -n 1
}

find_cuda_arch() {
  if [ -n "${VMC_CLANGD_ARCH:-}" ]; then
    echo "$VMC_CLANGD_ARCH"
  elif command -v nvidia-smi >/dev/null; then
    nvidia-smi --query-gpu=compute_cap --format=csv,noheader 2>/dev/null \
      | head -n 1 \
      | tr -d '. '
  fi
}

find_project_flags() {
  python3 - "$REPO_ROOT" "$1" <<'PY'
import json, shlex, sys

repo_root, compile_db = sys.argv[1], sys.argv[2]

with open(f"{compile_db}/compile_commands.json") as handle:
    entries = json.load(handle)

sources = (f"{repo_root}/src/", f"{repo_root}/tests/")
kept, seen = [], set()

for entry in entries:
    if not entry["file"].startswith(sources):
        continue

    args = shlex.split(entry.get("command") or "") or entry.get("arguments", [])

    for arg in args:
        if not arg.startswith(("-I", "-isystem", "-std=", "-D")):
            continue
        if arg in seen:
            continue
        seen.add(arg)
        kept.append(arg)
    break

print("\n".join(kept))
PY
}

COMPILE_DB="$(find_compile_db)"

if [ -z "$COMPILE_DB" ]; then
  echo "no compile_commands.json found; configure a build first" >&2
  exit 1
fi

PROJECT_FLAGS="$(find_project_flags "$COMPILE_DB" | sed 's/^/    - /')"

if [ -z "$PROJECT_FLAGS" ]; then
  echo "warning: no project sources in $COMPILE_DB, headers will rely on clangd inference" >&2
fi

substitute() {
  local placeholder="$1"
  local value="$2"

  if [ -n "$value" ]; then
    sed "s|$placeholder|$value|g"
  else
    grep -v "$placeholder"
  fi
}

expand_project_flags() {
  awk -v flags="$PROJECT_FLAGS" '
    /^  Add:[[:space:]]*$/ { pending = $0; next }
    {
      line = $0

      if (line ~ /@PROJECT_FLAGS@/) {
        if (flags == "") { next }
        line = flags
      }

      if (pending != "") { print pending; pending = "" }

      print line
    }
  '
}

CUDA_PATH_VALUE=""
CUDA_ARCH_VALUE=""
CCCL_INCLUDE_VALUE=""

if [ "$MODE" = "cuda" ]; then
  CUDA_PATH_VALUE="$(find_cuda_path)"
  CUDA_ARCH_VALUE="$(find_cuda_arch)"
  CCCL_INCLUDE_VALUE="$(find_cccl_include "$CUDA_PATH_VALUE")"

  if [ -z "$CUDA_PATH_VALUE" ]; then
    echo "warning: no CUDA toolkit found, letting clang search its defaults" >&2
  fi

  if [ -z "$CUDA_ARCH_VALUE" ]; then
    echo "warning: no GPU detected, falling back to clang's default arch" >&2
  fi
fi

{
  echo "# generated by scripts/clangd-mode.sh $MODE - edit .clangd-$MODE instead"
  substitute "@COMPILE_DB@" "$COMPILE_DB" < "$TEMPLATE" \
    | substitute "@CUDA_PATH@" "$CUDA_PATH_VALUE" \
    | substitute "@CUDA_ARCH@" "$CUDA_ARCH_VALUE" \
    | substitute "@CCCL_INCLUDE@" "$CCCL_INCLUDE_VALUE" \
    | expand_project_flags
} > "$TARGET"

echo "clangd mode: $MODE (db: $COMPILE_DB${CUDA_ARCH_VALUE:+, arch: sm_$CUDA_ARCH_VALUE})"
echo "restart the server to apply: F1 > 'clangd: Restart language server'"
